# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        # storage_id: session.storage.native
        cookie_secure: false
        cookie_samesite: lax

when@test:
    framework:
        # test: true
        # session:
        #     storage_factory_id: session.storage.factory.mock_file
