# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    disallow_search_engine_index: false
    
    session:
        handler_id: null
        # storage_id: session.storage.native
        cookie_secure: false
        cookie_samesite: lax

when@test:
    framework:
        # test: true
        # session:
        #     storage_factory_id: session.storage.factory.mock_file
tinymce:
    # The configurations mirror the TinyMCE attributes.
    # Learn more about each option in Tiny's documentation:
    # https://www.tiny.cloud/docs/tinymce/6/webcomponent-ref/
    skin: "oxide"
    content_css: "default"
    content_style: ""
    config: "tinymceAdditionalConfig"
    plugins: "advlist autolink link image media table lists"
    toolbar: "bold italic underline | bullist numlist"
    toolbar_mode: ""
    menubar: ""
    contextmenu: ""
    quickbars_insert_toolbar: ""
    quickbars_selection_toolbar: ""
    resize: ""
    icons: ""
    icons_url: ""
    setup: ""
    images_upload_url: "https://yoursite.com/upload"
    images_upload_route: ""
    images_upload_route_params: []
    images_upload_handler: ""
    images_upload_base_path: ""
    images_upload_credentials: "true"
    images_reuse_filename: ""
    powerpaste_word_import: ""
    powerpaste_html_import: ""
    powerpaste_allow_local_images: ""
    